# Generated by Django 3.0.1 on 2020-01-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200115_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
