# Generated by Django 3.0.1 on 2019-12-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.TextField(default='000-000-000'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='Missing pet'),
        ),
    ]
